# Custom variants for Fairy-Stockfish

[5x6chess:gardner]
maxRank = 6
maxFile = e
promotionRegionWhite = *6
promotionRegionBlack = *1
startFen = rnbqk/ppppp/5/5/PPPPP/RNBQK w - - 0 1

[4x5chess:gardner]
maxRank = 5
maxFile = d
promotionRegionWhite = *5
promotionRegionBlack = *1
startFen = rnbk/pppp/4/PPPP/RNBK w - - 0 1

[4x6chess:gardner]
maxRank = 6
maxFile = d
promotionRegionWhite = *6
promotionRegionBlack = *1
startFen = rnbk/pppp/4/4/PPPP/RNBK w - - 0 1
[5x6chess:gardner]
maxRank = 6
maxFile = e
promotionRegionWhite = *6
promotionRegionBlack = *1
startFen = rnbqk/ppppp/5/5/PPPPP/RNBQK w - - 0 1
